spring:
  application:
    name: eureka

eureka:
  client:
    # 是否将自己的路径注册到eureka上
    register-with-eureka: true
    # 是否需要从eureka中拉取数据
    fetch-registry: true
    service-url:
      # eureka服务端地址，将来客户端使用该地址和eureka进行通信
      defaultZone: http://eureka-8761:8761/eureka/,http://eureka-8762:8762/eureka/,http://eureka-8763:8763/eureka/
  server:
    # 自我保护
    enable-self-preservation: false
    # 自我保护阈值
    renewal-percent-threshold: 0.85
    # 剔除服务时间间隔
    eviction-interval-timer-in-ms: 1000
    # 关闭从readOnly读注册表
    use-read-only-response-cache: false
    # readWrite 和 readOnly 同步时间间隔
    response-cache-update-interval-ms: 1000

---
spring:
  profiles: 8761
server:
    port: 8761
eureka:
  instance:
    hostname: eureka-8761

---
spring:
  profiles: 8762
server:
  port: 8762
eureka:
  instance:
    hostname: eureka-8762

---
spring:
  profiles: 8763
server:
  port: 8763
eureka:
  instance:
    hostname: eureka-8763
