server:
  port: 8080

spring:
  application:
    name: api-passenger
#  main:
#    allow-circular-references: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-8761:8761/eureka/,http://eureka-8762:8762/eureka/,http://eureka-8763:8763/eureka/
    # 使能注册到Eureka，默认是true
    enabled: true
  instance:
    # 续约时间
    lease-renewal-interval-in-seconds: 30


