server:
  port: 8082

spring:
  application:
    name: service-sms
  datasource:
    #配置当前使用的数据源的操作类型
    type: com.alibaba.druid.pool.DruidDataSource
    #配置MySQL的驱动程序类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #数据库连接地址
    url: jdbc:mysql://localhost:3306/online-taxi?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    #数据库连接用户名
    username: root
    #数据库连接密码
    password: 123456
    #进行数据库连接池的配置
    dbcp2:
      #初始化提供的连接数
      initial-size: 5
      #数据库连接池的最小维持连接数
      min-idle: 5
      #最大的连接数
      max-total: 5
      #等待连接获取的最大超时时间
      max-wait-millis: 200
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

#mybatis配置
mybatis:
  mapper-locations:
    - classpath:mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://eureka-8761:8761/eureka/,http://eureka-8762:8762/eureka/,http://eureka-8763:8763/eureka/
    registry-fetch-interval-seconds: 30
    # 使能注册到Eureka，默认是true
    enabled: true
  instance:
    # 续约时间
    lease-renewal-interval-in-seconds: 30

---
spring:
  profiles: v1

eureka:
  instance:
    metadata-map:
      version: v1
server:
  #服务端口
  port: 8082
---
spring:
  profiles: v2

eureka:
  instance:
    metadata-map:
      version: v2
server:
  #服务端口
  port: 8084


